# Generated by Django 4.1.7 on 2023-03-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_car_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop', models.CharField(choices=[('C', 'City Customs'), ('D', 'Downtown Customs'), ('W', 'Westside Customs')], default='C', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
