# Generated by Django 4.1.7 on 2023-03-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tuning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuning',
            options={'ordering': ['-date']},
        ),
    ]
